name = "UNOFFICIAL ACE Compat - SOG PF";
picture = "logo.paa";
description = "UNOFFICIAL ACE compatibility for S.O.G. Prairie Fire";
tooltip = "UNOFFICIAL ACE Compat - SOG PF";
tooltipOwned = "UNOFFICIAL ACE Compat - SOG PF Owned";
overview = "UNOFFICIAL ACE Compat - SOG PF";
author = "Ragwolf";
overviewText = "UNOFFICIAL ACE Compat - SOG PF";
overviewFootnote = "";
